### ISSUE TITLE
Setup of CI system

### ISSUE THREAD

**Issue by danielksan81** [boschresearch/open-eot-agents#1]
Goal is to have a Continuous Integration system, which is able to perform checks and builds for incoming pull requests.
Systems to consider are CircleCI and githubs CI system.
Therefore build scripts needs to be available, which can be triggered either local or from the CI system to be used.

**Comment by hboukricha** [comment]
Let's use the GitHub Workflows ;-)

**Comment by danielksan81** [comment]
> Let's use the GitHub Workflows / GitHub Actions ;-)

Will have a look into it...
