### ISSUE TITLE
Implement the SSI communication method DIDcomm for AEA

### ISSUE THREAD

**Issue by l-wegner** [boschresearch/open-eot-agents#15]
As an AEA developer I want to initiate a connection with a service/ agent, which is published by a DID.

The component gets a DID Doc related to the DID and has to initiate the DIDComm protocol.
The output o the component should be a verification proof, the agent's endpoint and the agent's public key.

The component should enable the contract-net skill to communicate with agents published via DIDs.

**Comment by danielksan81** [comment]
not relevant anymore, as DIDcomm is not used anymore.
See #32
